# data.py

from typing import Optional

EVENTS = [
    {
        "id": 1,
        "name": "Jazz Evening at Marina Bay",
        "location": "Marina Beach",
        "type": "Music",
        "date": "Saturday",
        "time": "7 PM",
        "description": "Immerse yourself in soothing jazz tunes by the waves.",
        "image_url": "https://picsum.photos/600/900/?random=101",
    },
    {
        "id": 2,
        "name": "Art Fiesta: Chennai Colors",
        "location": "Cholamandal Artists' Village",
        "type": "Art",
        "date": "Friday",
        "time": "5 PM",
        "description": "Discover vibrant art inspired by Chennai's culture.",
        "image_url": "https://picsum.photos/600/900/?random=102",
    },
    {
        "id": 3,
        "name": "TechCon Chennai 2024",
        "location": "Trade Center",
        "type": "Technology",
        "date": "Monday",
        "time": "10 AM",
        "description": "Explore the latest innovations in technology.",
        "image_url": "https://picsum.photos/600/900/?random=103",
    },
    {
        "id": 4,
        "name": "Organic Farmers Market",
        "location": "Besant Nagar",
        "type": "Food",
        "date": "Saturday",
        "time": "9 AM",
        "description": "Shop fresh organic produce and local crafts.",
        "image_url": "https://picsum.photos/600/900/?random=104",
    },
    {
        "id": 5,
        "name": "Comedy Carnival",
        "location": "Phoenix MarketCity",
        "type": "Comedy",
        "date": "Thursday",
        "time": "8 PM",
        "description": "Laugh out loud at Chennai's top comedy acts.",
        "image_url": "https://picsum.photos/600/900/?random=105",
    },
    {
        "id": 6,
        "name": "Sunrise Yoga Workshop",
        "location": "Anna Nagar Tower Park",
        "type": "Health",
        "date": "Sunday",
        "time": "6 AM",
        "description": "Begin your day with rejuvenating yoga.",
        "image_url": "https://picsum.photos/600/900/?random=106",
    },
    {
        "id": 7,
        "name": "Literary Hangout",
        "location": "British Council Chennai",
        "type": "Literature",
        "date": "Wednesday",
        "time": "3 PM",
        "description": "Join fellow book lovers for engaging discussions.",
        "image_url": "https://picsum.photos/600/900/?random=107",
    },
    {
        "id": 8,
        "name": "Hackathon Weekend",
        "location": "SP Info City",
        "type": "Technology",
        "date": "Saturday",
        "time": "10 AM",
        "description": "Collaborate with tech enthusiasts and showcase innovations.",
        "image_url": "https://picsum.photos/600/900/?random=108",
    },
    {
        "id": 9,
        "name": "Acoustic Night",
        "location": "Adyar Cafe",
        "type": "Music",
        "date": "Friday",
        "time": "8 PM",
        "description": "Relax with live acoustic tunes at a cozy cafe.",
        "image_url": "https://picsum.photos/600/900/?random=109",
    },
    {
        "id": 10,
        "name": "Open Air Cinema",
        "location": "Elliot's Beach",
        "type": "Entertainment",
        "date": "Saturday",
        "time": "8 PM",
        "description": "Enjoy a classic film under the stars.",
        "image_url": "https://picsum.photos/600/900/?random=110",
    },
    {
        "id": 11,
        "name": "Carnatic Vocal Workshop",
        "location": "Ragas Hall",
        "type": "Music",
        "date": "Tuesday",
        "time": "6 PM",
        "description": "Learn the fundamentals of Carnatic music from experts.",
        "image_url": "https://picsum.photos/600/900/?random=111",
    },
    {
        "id": 12,
        "name": "South Indian Culinary Experience",
        "location": "Mylapore Kitchen",
        "type": "Food",
        "date": "Sunday",
        "time": "11 AM",
        "description": "Discover the art of making traditional South Indian dishes.",
        "image_url": "https://picsum.photos/600/900/?random=112",
    },
    {
        "id": 13,
        "name": "Fitness Fest",
        "location": "Guindy National Park",
        "type": "Health",
        "date": "Saturday",
        "time": "7 AM",
        "description": "Join fitness experts for a day of workouts and fun activities.",
        "image_url": "https://picsum.photos/600/900/?random=113",
    },
    {
        "id": 14,
        "name": "Street Food Crawl",
        "location": "T Nagar",
        "type": "Food",
        "date": "Friday",
        "time": "7 PM",
        "description": "Explore the best street food Chennai has to offer.",
        "image_url": "https://picsum.photos/600/900/?random=114",
    },
    {
        "id": 15,
        "name": "Beach Cleanup Drive",
        "location": "Marina Beach",
        "type": "Community",
        "date": "Sunday",
        "time": "6 AM",
        "description": "Join hands to keep our beaches clean and beautiful.",
        "image_url": "https://picsum.photos/600/900/?random=115",
    },
    {
        "id": 16,
        "name": "Live Instrumental Music",
        "location": "DakshinaChitra",
        "type": "Music",
        "date": "Saturday",
        "time": "6 PM",
        "description": "Experience soul-soothing instrumental music performances.",
        "image_url": "https://picsum.photos/600/900/?random=116",
    },
    {
        "id": 17,
        "name": "Classical Dance Recital",
        "location": "Kalakshetra Foundation",
        "type": "Dance",
        "date": "Thursday",
        "time": "7 PM",
        "description": "Witness the elegance of Bharatanatyam performed by maestros.",
        "image_url": "https://picsum.photos/600/900/?random=117",
    },
    {
        "id": 18,
        "name": "Street Art Festival",
        "location": "Egmore",
        "type": "Art",
        "date": "Saturday",
        "time": "10 AM",
        "description": "Watch artists transform the streets with vibrant murals.",
        "image_url": "https://picsum.photos/600/900/?random=118",
    },
    {
        "id": 19,
        "name": "Adventure Trek",
        "location": "Nagala Hills",
        "type": "Adventure",
        "date": "Sunday",
        "time": "5 AM",
        "description": "Embark on a thrilling trek through scenic trails.",
        "image_url": "https://picsum.photos/600/900/?random=119",
    },
    {
        "id": 20,
        "name": "Pottery Workshop",
        "location": "Adyar",
        "type": "Art",
        "date": "Wednesday",
        "time": "4 PM",
        "description": "Unleash your creativity and learn pottery-making techniques.",
        "image_url": "https://picsum.photos/600/900/?random=120",
    },
    {
        "id": 21,
        "name": "Photography Walk",
        "location": "George Town",
        "type": "Photography",
        "date": "Saturday",
        "time": "6 AM",
        "description": "Capture the essence of Chennai on an early morning photography walk.",
        "image_url": "https://picsum.photos/600/900/?random=121",
    },
    {
        "id": 22,
        "name": "Wine and Dine Evening",
        "location": "Anna Nagar Club",
        "type": "Food",
        "date": "Friday",
        "time": "7 PM",
        "description": "Indulge in fine dining paired with exquisite wines.",
        "image_url": "https://picsum.photos/600/900/?random=122",
    },
    {
        "id": 23,
        "name": "Coding Bootcamp",
        "location": "OMR Tech Park",
        "type": "Technology",
        "date": "Monday",
        "time": "9 AM",
        "description": "Sharpen your coding skills with hands-on projects.",
        "image_url": "https://picsum.photos/600/900/?random=123",
    },
    {
        "id": 24,
        "name": "Pongal Festival Celebration",
        "location": "Mylapore",
        "type": "Cultural",
        "date": "Saturday",
        "time": "10 AM",
        "description": "Celebrate Tamil Nadu's harvest festival with traditional activities.",
        "image_url": "https://picsum.photos/600/900/?random=124",
    },
    {
        "id": 25,
        "name": "Fitness Marathon",
        "location": "Marina Loop Road",
        "type": "Health",
        "date": "Sunday",
        "time": "5 AM",
        "description": "Join Chennai's biggest fitness marathon event.",
        "image_url": "https://picsum.photos/600/900/?random=125",
    },
    {
        "id": 26,
        "name": "Classic Car Rally",
        "location": "Nungambakkam High Road",
        "type": "Automobile",
        "date": "Sunday",
        "time": "9 AM",
        "description": "Marvel at classic and vintage cars on display.",
        "image_url": "https://picsum.photos/600/900/?random=126",
    },
    {
        "id": 27,
        "name": "Sustainable Living Workshop",
        "location": "Greenways Road",
        "type": "Environment",
        "date": "Wednesday",
        "time": "11 AM",
        "description": "Learn tips for an eco-friendly lifestyle.",
        "image_url": "https://picsum.photos/600/900/?random=127",
    },
    {
        "id": 28,
        "name": "Beach Volleyball Tournament",
        "location": "Thiruvanmiyur Beach",
        "type": "Sports",
        "date": "Saturday",
        "time": "4 PM",
        "description": "Watch exciting matches by Chennai's top volleyball teams.",
        "image_url": "https://picsum.photos/600/900/?random=128",
    },
    {
        "id": 29,
        "name": "Startup Meet & Greet",
        "location": "Guindy Industrial Estate",
        "type": "Business",
        "date": "Thursday",
        "time": "6 PM",
        "description": "Network with entrepreneurs and industry experts.",
        "image_url": "https://picsum.photos/600/900/?random=129",
    },
    {
        "id": 30,
        "name": "Drumming Circle",
        "location": "Besant Nagar Beach",
        "type": "Music",
        "date": "Friday",
        "time": "7 PM",
        "description": "Join a rhythmic evening of community drumming.",
        "image_url": "https://picsum.photos/600/900/?random=130",
    },
    {
        "id": 31,
        "name": "Origami Workshop",
        "location": "Nungambakkam Art Center",
        "type": "Art",
        "date": "Tuesday",
        "time": "3 PM",
        "description": "Master the art of paper folding with expert guidance.",
        "image_url": "https://picsum.photos/600/900/?random=131",
    },
    {
        "id": 32,
        "name": "Bird Watching Walk",
        "location": "Vedanthangal Bird Sanctuary",
        "type": "Nature",
        "date": "Sunday",
        "time": "6 AM",
        "description": "Spot exotic birds in their natural habitat.",
        "image_url": "https://picsum.photos/600/900/?random=132",
    },
    {
        "id": 33,
        "name": "Flea Market",
        "location": "Velachery",
        "type": "Shopping",
        "date": "Saturday",
        "time": "11 AM",
        "description": "Shop unique handicrafts and quirky items.",
        "image_url": "https://picsum.photos/600/900/?random=133",
    },
    {
        "id": 34,
        "name": "Stand-Up Comedy Open Mic",
        "location": "Royapettah",
        "type": "Comedy",
        "date": "Thursday",
        "time": "8 PM",
        "description": "Catch emerging comedians at this fun-filled open mic night.",
        "image_url": "https://picsum.photos/600/900/?random=134",
    },
    {
        "id": 35,
        "name": "Astrology and Wellness Fair",
        "location": "T Nagar Hall",
        "type": "Spirituality",
        "date": "Saturday",
        "time": "10 AM",
        "description": "Discover your destiny and learn wellness tips.",
        "image_url": "https://picsum.photos/600/900/?random=135",
    },
    {
        "id": 36,
        "name": "Kite Flying Festival",
        "location": "Marina Beach",
        "type": "Family",
        "date": "Sunday",
        "time": "4 PM",
        "description": "Bring your family and watch vibrant kites fill the sky.",
        "image_url": "https://picsum.photos/600/900/?random=136",
    },
    {
        "id": 37,
        "name": "Classical Music Concert",
        "location": "Narada Gana Sabha",
        "type": "Music",
        "date": "Saturday",
        "time": "7 PM",
        "description": "An enchanting evening of Carnatic music.",
        "image_url": "https://picsum.photos/600/900/?random=137",
    },
    {
        "id": 38,
        "name": "Cultural Dance Festival",
        "location": "Mylapore Fine Arts Club",
        "type": "Dance",
        "date": "Friday",
        "time": "6 PM",
        "description": "Celebrate India's diverse dance forms.",
        "image_url": "https://picsum.photos/600/900/?random=138",
    },
    {
        "id": 39,
        "name": "DIY Craft Workshop",
        "location": "Velachery Community Hall",
        "type": "Craft",
        "date": "Wednesday",
        "time": "4 PM",
        "description": "Get hands-on with fun and creative DIY crafts.",
        "image_url": "https://picsum.photos/600/900/?random=139",
    },
    {
        "id": 40,
        "name": "Martial Arts Demonstration",
        "location": "Anna University Grounds",
        "type": "Sports",
        "date": "Saturday",
        "time": "5 PM",
        "description": "Witness breathtaking martial arts performances.",
        "image_url": "https://picsum.photos/600/900/?random=140",
    },
    {
        "id": 41,
        "name": "Heritage Walk",
        "location": "Fort St. George",
        "type": "History",
        "date": "Sunday",
        "time": "8 AM",
        "description": "Explore Chennai's rich colonial history.",
        "image_url": "https://picsum.photos/600/900/?random=141",
    },
    {
        "id": 42,
        "name": "Movie Marathon Night",
        "location": "Anna Nagar Cinema",
        "type": "Entertainment",
        "date": "Saturday",
        "time": "9 PM",
        "description": "Catch back-to-back screenings of your favorite movies.",
        "image_url": "https://picsum.photos/600/900/?random=142",
    },
    {
        "id": 43,
        "name": "Stand-Up Poetry Slam",
        "location": "Alwarpet",
        "type": "Literature",
        "date": "Tuesday",
        "time": "6 PM",
        "description": "Listen to inspiring poetry and performances.",
        "image_url": "https://picsum.photos/600/900/?random=143",
    },
    {
        "id": 44,
        "name": "Beach Bonfire Night",
        "location": "Thiruvanmiyur Beach",
        "type": "Entertainment",
        "date": "Friday",
        "time": "8 PM",
        "description": "Unwind by the bonfire with music and games.",
        "image_url": "https://picsum.photos/600/900/?random=144",
    },
    {
        "id": 45,
        "name": "Meditation Retreat",
        "location": "Vandalur Hills",
        "type": "Spirituality",
        "date": "Sunday",
        "time": "7 AM",
        "description": "Find your inner peace through guided meditation.",
        "image_url": "https://picsum.photos/600/900/?random=145",
    },
    {
        "id": 46,
        "name": "Outdoor Yoga Festival",
        "location": "Besant Nagar Beach",
        "type": "Health",
        "date": "Saturday",
        "time": "6 AM",
        "description": "Join hundreds in a refreshing yoga session by the beach.",
        "image_url": "https://picsum.photos/600/900/?random=146",
    },
    {
        "id": 47,
        "name": "Astronomy Night",
        "location": "Guindy National Park",
        "type": "Science",
        "date": "Friday",
        "time": "9 PM",
        "description": "Gaze at the stars with telescopes and expert guidance.",
        "image_url": "https://picsum.photos/600/900/?random=147",
    },
    {
        "id": 48,
        "name": "Street Theatre Performance",
        "location": "T Nagar",
        "type": "Theatre",
        "date": "Saturday",
        "time": "5 PM",
        "description": "Watch powerful street theatre performances addressing social issues.",
        "image_url": "https://picsum.photos/600/900/?random=148",
    },
    {
        "id": 49,
        "name": "Chennai Music Festival",
        "location": "Multiple Venues",
        "type": "Music",
        "date": "Thursday",
        "time": "6 PM",
        "description": "Experience the soul of Chennai with traditional music.",
        "image_url": "https://picsum.photos/600/900/?random=149",
    },
    {
        "id": 50,
        "name": "Nature Photography Workshop",
        "location": "Vedanthangal Bird Sanctuary",
        "type": "Photography",
        "date": "Saturday",
        "time": "7 AM",
        "description": "Learn the art of capturing nature's beauty through your lens.",
        "image_url": "https://picsum.photos/600/900/?random=150",
    }
]


USERS = [
    {
        "id": 1,
        "username": "Rohit yadav",
        "email": "rohit@example.com",
        "interests": ["Music", "Technology", "Health"],
        "community_ids": [1, 2],
    },
    {
        "id": 2,
        "username": "jane_smith",
        "email": "jane@example.com",
        "interests": ["Art", "Literature", "Photography"],
        "community_ids": [3],
    },
    {
        "id": 3,
        "username": "joh_doe",
        "email": "joh@example.com",
        "interests": ["Music", "Technology", "Health"],
        "community_ids": [1, 2],
    },
    # Additional 30 Users
    {
        "id": 4,
        "username": "alice_wonder",
        "email": "alice.wonder@example.com",
        "interests": ["Travel", "Cooking", "Yoga"],
        "community_ids": [4, 5],
    },
    {
        "id": 5,
        "username": "bob_builder",
        "email": "bob.builder@example.com",
        "interests": ["DIY", "Gardening", "Technology"],
        "community_ids": [2, 6],
    },
    {
        "id": 6,
        "username": "charlie_brown",
        "email": "charlie.brown@example.com",
        "interests": ["Comics", "Music", "Sports"],
        "community_ids": [1, 7],
    },
    {
        "id": 7,
        "username": "diana_prince",
        "email": "diana.prince@example.com",
        "interests": ["Fitness", "Health", "Travel"],
        "community_ids": [4, 5],
    },
    {
        "id": 8,
        "username": "edward_scissorhands",
        "email": "edward.scissorhands@example.com",
        "interests": ["Art", "Music", "Technology"],
        "community_ids": [1, 3, 2],
    },
    {
        "id": 9,
        "username": "fiona_shrek",
        "email": "fiona.shrek@example.com",
        "interests": ["Cooking", "Gardening", "Literature"],
        "community_ids": [5, 8],
    },
    {
        "id": 10,
        "username": "george_clooney",
        "email": "george.clooney@example.com",
        "interests": ["Cinema", "Photography", "Travel"],
        "community_ids": [3, 7],
    },
    {
        "id": 11,
        "username": "hannah_montana",
        "email": "hannah.montana@example.com",
        "interests": ["Music", "Dance", "Fitness"],
        "community_ids": [1, 4],
    },
    {
        "id": 12,
        "username": "ian_fleming",
        "email": "ian.fleming@example.com",
        "interests": ["Literature", "Travel", "Technology"],
        "community_ids": [3, 2],
    },
    {
        "id": 13,
        "username": "julia_roberts",
        "email": "julia.roberts@example.com",
        "interests": ["Cinema", "Art", "Health"],
        "community_ids": [3, 1],
    },
    {
        "id": 14,
        "username": "kevin_bacon",
        "email": "kevin.bacon@example.com",
        "interests": ["Music", "Sports", "Technology"],
        "community_ids": [1, 2, 7],
    },
    {
        "id": 15,
        "username": "linda_carol",
        "email": "linda.carol@example.com",
        "interests": ["Cooking", "Art", "Photography"],
        "community_ids": [5, 3],
    },
    {
        "id": 16,
        "username": "michael_scott",
        "email": "michael.scott@example.com",
        "interests": ["Comedy", "Writing", "Sports"],
        "community_ids": [9, 7],
    },
    {
        "id": 17,
        "username": "nina_dobrev",
        "email": "nina.dobrev@example.com",
        "interests": ["Dance", "Health", "Travel"],
        "community_ids": [4, 5],
    },
    {
        "id": 18,
        "username": "oliver_twist",
        "email": "oliver.twist@example.com",
        "interests": ["Literature", "Cooking", "Music"],
        "community_ids": [3, 5],
    },
    {
        "id": 19,
        "username": "paula_abdul",
        "email": "paula.abdul@example.com",
        "interests": ["Dance", "Fitness", "Music"],
        "community_ids": [4, 1],
    },
    {
        "id": 20,
        "username": "quincy_jones",
        "email": "quincy.jones@example.com",
        "interests": ["Music", "Technology", "Cinema"],
        "community_ids": [1, 2, 3],
    },
    {
        "id": 21,
        "username": "rachel_green",
        "email": "rachel.green@example.com",
        "interests": ["Fashion", "Photography", "Art"],
        "community_ids": [3, 8],
    },
    {
        "id": 22,
        "username": "steve_jobs",
        "email": "steve.jobs@example.com",
        "interests": ["Technology", "Innovation", "Design"],
        "community_ids": [2, 10],
    },
    {
        "id": 23,
        "username": "tina_fey",
        "email": "tina.fey@example.com",
        "interests": ["Comedy", "Writing", "Cinema"],
        "community_ids": [9, 3],
    },
    {
        "id": 24,
        "username": "ursula_le_guin",
        "email": "ursula.leguin@example.com",
        "interests": ["Literature", "Art", "Photography"],
        "community_ids": [3, 8],
    },
    {
        "id": 25,
        "username": "victor_frankenstein",
        "email": "victor.frankenstein@example.com",
        "interests": ["Science", "Technology", "Literature"],
        "community_ids": [2, 3],
    },
    {
        "id": 26,
        "username": "wendy_darling",
        "email": "wendy.darling@example.com",
        "interests": ["Travel", "Literature", "Art"],
        "community_ids": [3, 4],
    },
    {
        "id": 27,
        "username": "xander_harris",
        "email": "xander.harris@example.com",
        "interests": ["Gaming", "Technology", "Health"],
        "community_ids": [2, 11],
    },
    {
        "id": 28,
        "username": "yvonne_starr",
        "email": "yvonne.starr@example.com",
        "interests": ["Music", "Fashion", "Photography"],
        "community_ids": [1, 8],
    },
    {
        "id": 29,
        "username": "zachary_levi",
        "email": "zachary.levi@example.com",
        "interests": ["Acting", "Dance", "Cinema"],
        "community_ids": [9, 3],
    },
    {
        "id": 30,
        "username": "amber_heard",
        "email": "amber.heard@example.com",
        "interests": ["Acting", "Art", "Travel"],
        "community_ids": [3, 4],
    },
    {
        "id": 31,
        "username": "bruce_wayne",
        "email": "bruce.wayne@example.com",
        "interests": ["Business", "Technology", "Fitness"],
        "community_ids": [2, 5],
    },
    {
        "id": 32,
        "username": "catherine_zeta",
        "email": "catherine.zeta@example.com",
        "interests": ["Acting", "Dance", "Health"],
        "community_ids": [9, 4],
    },
    {
        "id": 33,
        "username": "daniel_radcliffe",
        "email": "daniel.radcliffe@example.com",
        "interests": ["Acting", "Literature", "Travel"],
        "community_ids": [3, 4],
    },
]

COMMUNITIES = [
    {
        "id": 1,
        "name": "Music Lovers",
        "description": "A community for people who love all genres of music.",
        "interests": ["Music", "Concerts", "Live Performances"],
    },
    {
        "id": 2,
        "name": "Tech Enthusiasts",
        "description": "Discuss the latest in technology and innovation.",
        "interests": ["Technology", "Coding", "Gadgets"],
    },
    {
        "id": 3,
        "name": "Art & Photography",
        "description": "Share and appreciate art and photography.",
        "interests": ["Art", "Photography", "Creative Writing"],
    },
    # Additional 30 Communities
    {
        "id": 4,
        "name": "Health and Wellness",
        "description": "A community focused on healthy living and wellness.",
        "interests": ["Health", "Fitness", "Nutrition"],
    },
    {
        "id": 5,
        "name": "Culinary Arts",
        "description": "Explore the world of cooking and gastronomy.",
        "interests": ["Cooking", "Baking", "Food Photography"],
    },
    {
        "id": 6,
        "name": "DIY Crafts",
        "description": "For those who love to create and build things themselves.",
        "interests": ["DIY", "Crafting", "Home Improvement"],
    },
    {
        "id": 7,
        "name": "Sports Fans",
        "description": "Discuss your favorite sports and teams.",
        "interests": ["Sports", "Fitness", "Outdoor Activities"],
    },
    {
        "id": 8,
        "name": "Creative Writers",
        "description": "A place for writers to share and critique their work.",
        "interests": ["Writing", "Literature", "Storytelling"],
    },
    {
        "id": 9,
        "name": "Comedy Club",
        "description": "Share jokes, funny stories, and enjoy a good laugh.",
        "interests": ["Comedy", "Humor", "Stand-up"],
    },
    {
        "id": 10,
        "name": "Innovators Hub",
        "description": "Collaborate on innovative projects and ideas.",
        "interests": ["Innovation", "Entrepreneurship", "Technology"],
    },
    {
        "id": 11,
        "name": "Gaming Zone",
        "description": "Discuss the latest games and gaming strategies.",
        "interests": ["Gaming", "Esports", "Game Development"],
    },
    {
        "id": 12,
        "name": "Book Club",
        "description": "Read and discuss books across various genres.",
        "interests": ["Reading", "Literature", "Discussion"],
    },
    {
        "id": 13,
        "name": "Travel Enthusiasts",
        "description": "Share travel experiences and tips.",
        "interests": ["Travel", "Adventure", "Culture"],
    },
    {
        "id": 14,
        "name": "Photography Masters",
        "description": "Enhance your photography skills and share your work.",
        "interests": ["Photography", "Editing", "Creative Arts"],
    },
    {
        "id": 15,
        "name": "Fitness Freaks",
        "description": "Stay motivated and share fitness routines.",
        "interests": ["Fitness", "Workout", "Health"],
    },
    {
        "id": 16,
        "name": "Tech Innovators",
        "description": "Explore cutting-edge technology and innovations.",
        "interests": ["Technology", "Innovation", "Gadgets"],
    },
    {
        "id": 17,
        "name": "Music Producers",
        "description": "Collaborate and discuss music production techniques.",
        "interests": ["Music Production", "Sound Engineering", "Beats"],
    },
    {
        "id": 18,
        "name": "Nature Lovers",
        "description": "Appreciate and protect the beauty of nature.",
        "interests": ["Nature", "Hiking", "Environmentalism"],
    },
    {
        "id": 19,
        "name": "Entrepreneurs Network",
        "description": "Connect with like-minded entrepreneurs.",
        "interests": ["Entrepreneurship", "Business", "Startups"],
    },
    {
        "id": 20,
        "name": "Language Learners",
        "description": "Learn and practice new languages together.",
        "interests": ["Languages", "Education", "Cultural Exchange"],
    },
    {
        "id": 21,
        "name": "Mindfulness & Meditation",
        "description": "Practice mindfulness and meditation techniques.",
        "interests": ["Meditation", "Mindfulness", "Mental Health"],
    },
    {
        "id": 22,
        "name": "Science Explorers",
        "description": "Dive into the wonders of science and discovery.",
        "interests": ["Science", "Research", "Astronomy"],
    },
    {
        "id": 23,
        "name": "Fashion Forward",
        "description": "Stay updated with the latest fashion trends.",
        "interests": ["Fashion", "Design", "Styling"],
    },
    {
        "id": 24,
        "name": "Film Buffs",
        "description": "Discuss and review the latest films.",
        "interests": ["Cinema", "Film Reviews", "Directing"],
    },
    {
        "id": 25,
        "name": "Coding Dojo",
        "description": "Improve your coding skills through practice and collaboration.",
        "interests": ["Coding", "Programming", "Software Development"],
    },
    {
        "id": 26,
        "name": "Pet Lovers",
        "description": "Share stories and tips about your furry friends.",
        "interests": ["Pets", "Animal Care", "Pet Training"],
    },
    {
        "id": 27,
        "name": "Astronomy Club",
        "description": "Explore the universe and celestial events.",
        "interests": ["Astronomy", "Space", "Stargazing"],
    },
    {
        "id": 28,
        "name": "Urban Explorers",
        "description": "Discover and document urban landscapes.",
        "interests": ["Urban Exploration", "Photography", "Architecture"],
    },
    {
        "id": 29,
        "name": "Sustainable Living",
        "description": "Promote and discuss sustainable lifestyle choices.",
        "interests": ["Sustainability", "Eco-friendly", "Green Living"],
    },
    {
        "id": 30,
        "name": "Creative Coding",
        "description": "Combine creativity with coding projects.",
        "interests": ["Creative Coding", "Artistic Programming", "Interactive Design"],
    },
    {
        "id": 31,
        "name": "Digital Nomads",
        "description": "Connect with fellow digital nomads around the world.",
        "interests": ["Remote Work", "Travel", "Lifestyle"],
    },
    {
        "id": 32,
        "name": "Book Writers",
        "description": "Collaborate and share insights on writing books.",
        "interests": ["Writing", "Publishing", "Storytelling"],
    },
    {
        "id": 33,
        "name": "Eco Warriors",
        "description": "Advocate for environmental protection and activism.",
        "interests": ["Environmentalism", "Activism", "Sustainability"],
    },
]
